version: "3.7"

services:
  db:
    container_name: postgres_db
    image: postgres:11.2
    volumes:
      - django_data_volume:/var/lib/postgresql/data
  rest_api:
    container_name: portfolio_rest_api
    build: 
      context: ./django
      dockerfile: DockerfilePython
    expose:
      - "3031"
    restart: always
    command: bash -c "python manage.py migrate && gunicorn my_docker_project.wsgi -b 0.0.0.0:3031"
    volumes:
      - ./django/portfolio_rest_api:/django
      - "staticdata:/django/static/"
    tty: true
    depends_on:
      - db
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - "./nginx/:/etc/nginx/"
      - "staticdata:/django/static/"
    depends_on:
      - rest_api
  web_front:
    container_name: portfolio_web_front
    build:
      context: .
      dockerfile: DockerfileNode
    volumes:
      - ./django/portfolio_web_front:/django
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - nginx
volumes:
  django_data_volume:
  staticdata: