version: '3'

services:

  web:
    build:
      context: ./ #実行に依存関係があるため
      dockerfile: ./web/Dockerfile
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - 8000:8000
    volumes:
      - ./web/logs/nginx/:/var/log/nginx/ #ホスト：コンテナ
      - ./web/uwsgi_params:/etc/nginx/uwsgi_params
      - ./api/static:/var/www/static/ #apiが必要
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: 'sh /server/start.sh' #シェルスクリプトファイルは後ほど作成
    expose: #コンテナ内部でやりとりするためのポート公開設定
      - "8001"
    volumes:
      - ./api:/server/

  front:
    build:
      context: ./front
    command: 'sh /app/start.sh'
    volumes:
      - ./front:/app/:cached
      - ./front/node_modules:/app/node_modules
    ports:
      - "8080:8080"