version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports: #コンテナ内部でやりとりするためのポート公開設定
      - 8000:8000
      - 8080:8080
    tty: true
    stdin_open: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/server/
