version: "3"

services:
  db:
    container_name: postgres_db
    image: postgres:11.2
    volumes:
      - django_data_volume:/var/lib/postgresql/data
  rest_api:
    container_name: portfolio_rest_api
    build:
      context: .
      dockerfile: DockerfilePython
    restart: always
    volumes:
      - ./code/portfolio_rest_api:/code
    command: gunicorn portfolio_rest_api.wsgi:application --bind 0.0.0.0:8000
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - "./nginx/:/etc/nginx/"
      - ./src/static:/static
    depends_on:
      - rest_api
  web_front:
    container_name: portfolio_web_front
    build:
      context: .
      dockerfile: DockerfileNode
    volumes:
      - ./code/django_web_front:/code
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - rest_api
volumes:
  django_data_volume: