version: "3"

services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    command: yarn run serve
    volumes:
      - ./front:/myapp
      - ./myapp/node_modules
    ports:
      - "8080:8080"
    container_name: front
    tty: true

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    image: python:3.7
    volumes:
      - ./api/:/api/src/app
    container_name: api
    tty: true
    working_dir: /api/src/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
