# Generated by Django 3.0.6 on 2020-06-29 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category_name')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='thumbnail')),
                ('lead_text', models.TextField(verbose_name='lead_text')),
                ('main_text', models.TextField(verbose_name='main_text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.Category', verbose_name='Category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
